name: Pack and Publish Nuget Package

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"
env:
  VERSION: 1.0.0

defaults:
  run:
    working-directory: ./src/MudBlazor
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Set version variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Setup dotnet version
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Pack nuget package
      run: dotnet pack -c Release --output nupkgs /p:PackageVersion=$VERSION
    - name: Publish nuget package
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json